HOOK-3244 Introduce action
leanix/integration-api-default-config-action pull request #1
Opened 2021-07-05 06:09 UTC by romansaul

2021-07-06 12:40 UTC, dan-leanix requested changes

2021-07-06 12:40 UTC, dan-leanix commented on .github/workflows/build.yml
> +        name: leanix/integration-api-default-config-action
```suggestion
```
You can keep it, but per default you don't need it as the repo name does not contain `leanix`. For instance, `leanix-integration-api` needs the `with: name` option.

2021-07-06 12:40 UTC, dan-leanix commented on Dockerfile
> +    apt-get clean
I would combine both RUN steps into one.

2021-07-06 13:45 UTC, rwe17 approved these changes
I still have some questions, but i assume this PR is a good starting point to start the remaining configuration on our side and do some tests.

2021-07-06 13:45 UTC, rwe17 commented on entrypoint.sh
> +az login --service-principal -u $ARM_CLIENT_ID -p $ARM_CLIENT_SECRET --tenant $ARM_TENANT_ID
Why is `AZURE_CLIENT_ID` exported and only ARM_CLIENT_SECRET is used inside the script? Do i oversee something?

2021-07-06 13:45 UTC, rwe17 commented on entrypoint.sh
> +NEW_CONFIG_LOCATION=/github/workspace/${INPUT_DEFAULT_CONFIG_FILE}
Is `/github/workspace/` a directory, we need to create later in our leanix-integration-api project?

2021-07-06 13:55 UTC, oaquijad approved these changes
This is the first step in order to create a new integration-api default configuration using this action, right? (Because it is still a TODO to actually create or update this default configuration).

2021-07-06 15:50 UTC, romansaul commented on README.md
> +  uses: leanix/integration-api-default-config-action@master
Good catch!

2021-07-06 15:52 UTC, romansaul commented on entrypoint.sh
> +NEW_CONFIG_LOCATION=/github/workspace/${INPUT_DEFAULT_CONFIG_FILE}
The action is used in the repo of the connector. All files from that repo are mounted at /github/workspace in the container which is the runtime of the action.

2021-07-06 15:54 UTC, romansaul commented
> This is the first step in order to create a new integration-api default configuration using this action, right? (Because it is still a TODO to actually create or update this default configuration).

Yes, the TODOs should be replaced in the course of working on the sibling Sailors ticket https://leanix.atlassian.net/browse/INTG-2256

2021-07-06 15:59 UTC, romansaul commented on entrypoint.sh
> +az login --service-principal -u $ARM_CLIENT_ID -p $ARM_CLIENT_SECRET --tenant $ARM_TENANT_ID
Yes, I'm also wondering. I think line 19-31 are a copy&paste error and can be removed.

2021-07-07 06:53 UTC, rwe17 approved these changes

2021-07-08 12:47 UTC, romansaul commented on Dockerfile
> +    apt-get clean
Done

2021-07-08 12:50 UTC, romansaul commented on README.md
> +  uses: leanix/integration-api-default-config-action@master
Fixed.

2021-07-08 12:50 UTC, romansaul commented on entrypoint.sh
> +az login --service-principal -u $ARM_CLIENT_ID -p $ARM_CLIENT_SECRET --tenant $ARM_TENANT_ID
Removed.

2021-07-08 12:56 UTC, dan-leanix approved these changes

2021-07-08 13:00 UTC, merged